### ISSUE TITLE
Problem z sandboxem

### ISSUE THREAD

**Issue by mareklat** [awronski/allegro-nice-api#1]
Witam,

Mój problem polega na tym, że nie mogę zbudować api z powodu tego błędu:

```
Exception in thread "main" javax.xml.ws.WebServiceException: Method doGetItemsImages is exposed as WebMethod, but there is no corresponding wsdl operation with name {https://webapi.allegro.pl/service.php}doGetItemsImages in the wsdl:portType{urn:SandboxWebApi}servicePort
	at com.sun.xml.internal.ws.model.JavaMethodImpl.freeze(JavaMethodImpl.java:367)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl.freeze(AbstractSEIModelImpl.java:105)
	at com.sun.xml.internal.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:320)
	at com.sun.xml.internal.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:85)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:59)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:43)
	at com.sun.xml.internal.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:105)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:875)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:892)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:855)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:435)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:404)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:386)
	at javax.xml.ws.Service.getPort(Service.java:119)
	at com.apwglobal.nice.service.AllegroNiceApi.createAllegro(AllegroNiceApi.java:70)
	at com.apwglobal.nice.service.AllegroNiceApi.<init>(AllegroNiceApi.java:49)
	at com.apwglobal.nice.service.AllegroNiceApi.<init>(AllegroNiceApi.java:31)
	at com.apwglobal.nice.service.AllegroNiceApi$Builder.build(AllegroNiceApi.java:210)
	at pl.ws.data.fake.AllegroShop.main(AllegroShop.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Systuacja występuje jedynie przy sandboxie. Domyślam się, że jest to spowodowane błędem(?) Allegro. Jednak czy jest możliwość obejścia tego? Będę bardzo wdzięczny za pomoc.

**Comment by awronski** [comment]
Cześć,

Sprawdziłem przed momentem i API się buduje. Uruchamiałem też część testów i jest ok.

1. Na jakim branchu jesteś? Powinieneś być na allegro-nice-api-2.1.0. Tylko ten jest utrzymywany.
2. Jaką komendą dokładnie budujesz?

Zrób sobie pulla, poprawiłem 2 drobne rzeczy.

**Comment by mareklat** [comment]
Dzięki za odpowiedź.

Ad 1. Byłem na masterze, przeniosłem się na 2.1.0
Ad 2. Pisząc o budowaniu, chodziło mi o buildera:
```
AllegroNiceApi api = new AllegroNiceApi.Builder()
                .conf(conf)
                .cred(cred)
                .test(true)
                .build();
```
Przełączyłem sie na inną gałąź i zrobiłem pula jednak błąd nadal występuje, ale teraz komunikat dotyczy innej metody wsdl:

```
Exception in thread "main" javax.xml.ws.WebServiceException: Method doGetItemsImages is exposed as WebMethod, but there is no corresponding wsdl operation with name {https://webapi.allegro.pl/service.php}doGetItemsImages in the wsdl:portType{urn:SandboxWebApi}servicePort
	at com.sun.xml.internal.ws.model.JavaMethodImpl.freeze(JavaMethodImpl.java:367)
	at com.sun.xml.internal.ws.model.AbstractSEIModelImpl.freeze(AbstractSEIModelImpl.java:105)
	at com.sun.xml.internal.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:320)
	at com.sun.xml.internal.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:85)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:59)
	at com.sun.xml.internal.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:43)
	at com.sun.xml.internal.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:105)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:875)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:892)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:855)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:435)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:404)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:386)
	at javax.xml.ws.Service.getPort(Service.java:119)
	at com.apwglobal.nice.service.AllegroNiceApi.createAllegro(AllegroNiceApi.java:73)
	at com.apwglobal.nice.service.AllegroNiceApi.<init>(AllegroNiceApi.java:51)
	at com.apwglobal.nice.service.AllegroNiceApi.<init>(AllegroNiceApi.java:32)
	at com.apwglobal.nice.service.AllegroNiceApi$Builder.build(AllegroNiceApi.java:236)
	at pl.ws.data.fake.AllegroShop.main(AllegroShop.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Kod, którym uruchamiam w celu przetestowania działania:
```
int countryId = 1;
Configuration conf = new Configuration(countryId);
Credentials cred = new Credentials(1, "MarcusL", "k54OHnTU", "s73f25a1");

AllegroNiceApi api = new AllegroNiceApi.Builder()
		.conf(conf)
		.cred(cred)
		.test(true)
		.build();

api.login()
	.getCategories()
	.forEach(category -> System.out.println(category.getCatName()));
```

**Comment by awronski** [comment]
Rozumiem, że chcesz korzystać z sandboxa?
WSDL sandboxa jest inny niż WSDL produkcyjnego allegro. Niestety tak to zrobili.

Konsekwencją tego jest to, że trzeba generować osobne klasy w zależności od tego czy chcesz budować aplikację na produkcję czy aplikację na sandbox. 

Ty wygenerowałeś service na produkcję, ale testujesz go na sandboxie i dlatego nie działa. (Są inne metody) U Ciebie jest (produkcja)
https://webapi.allegro.pl/service.php

a powinno być:
https://webapi.allegro.pl.webapisandbox.pl/service.php?wsdl

By Ci zadziałało musisz wygenerować klasy allegro w ten sposób:
mvn clean compile -P testprof

A jak będziesz chciał wrócić na produkcję to wystarczy:
mvn clean compile

**Comment by mareklat** [comment]
Tak, chciałem skorzystać ze sandboxa. Teraz dopiero do mnie dotarła ta informacja z README. Faktycznie, pomogło. Teraz działa bez zarzutów:) Przepraszam za niepotrzebne zawrócenie głowy.

Przy okazji chciałem Ci podziękować za kawał świetnej roboty z tą biblioteką. Teraz na myśl o tym, że miałbym mieć cokolwiek do czynienia z ich api nie powoduje już u mnie odruchów wymiotnych :)

Pozdrawiam!
